# Generated by Django 5.1.3 on 2025-02-11 14:47

import django.core.validators
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('P', 'Programada'), ('C', 'Cancelada'), ('F', 'Finalizada')], default='P', help_text='Estado de la clase: Programada, Cancelada o Finalizada.', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZÀ-ÿ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[gestion.models.validar_cedula]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZÀ-ÿ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[gestion.models.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZÀ-ÿ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[gestion.models.validar_cedula]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZÀ-ÿ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.CharField(max_length=10, validators=[gestion.models.validar_telefono]),
        ),
    ]
